"""add address column

Revision ID: 8550e98fed81
Revises: d96c7210c70f
Create Date: 2026-04-08 16:52:01.795230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8550e98fed81'
down_revision: Union[str, Sequence[str], None] = 'd96c7210c70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('address', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'address')
    # ### end Alembic commands ###
