"""add tag

Revision ID: 96fbd4e4d681
Revises: 62dd79219aeb
Create Date: 2026-04-16 19:07:14.608171

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '96fbd4e4d681'
down_revision: Union[str, Sequence[str], None] = '62dd79219aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', postgresql.ENUM('express', 'standard', 'fragile', 'heavy', 'international', 'domestic', 'temperature_sensitive', 'gift', 'return', 'documents', name='tagname', create_type=False), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    op.execute("""
        INSERT INTO tag (id, name, instruction) VALUES
        (gen_random_uuid(), 'express',               'Handle with priority — deliver within 24 hours'),
        (gen_random_uuid(), 'standard',              'Standard handling and delivery timeline applies'),
        (gen_random_uuid(), 'fragile',               'Handle with care — avoid stacking or dropping'),
        (gen_random_uuid(), 'heavy',                 'Use mechanical assistance — weight exceeds safe manual limit'),
        (gen_random_uuid(), 'international',         'Requires customs documentation and border clearance'),
        (gen_random_uuid(), 'domestic',              'Domestic route only — no cross-border processing required'),
        (gen_random_uuid(), 'temperature_sensitive', 'Keep between 2°C and 8°C throughout transit'),
        (gen_random_uuid(), 'gift',                  'Do not open — contains gift, include gift receipt if present'),
        (gen_random_uuid(), 'return',                'Return shipment — deliver to sender address on label'),
        (gen_random_uuid(), 'documents',             'Contains legal documents — keep dry and do not fold')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
